name:
channels:
  - conda-forge
  - bioconda
  - fastai
dependencies:
  - python=3.10
  - ca-certificates
  - openssl
  - python-dotenv
  - ipykernel
  - jupyter
  - nbdev
  - gh
  - numpy
  - matplotlib
  - fastapi
  - uvicorn